[04/Jan/2019 15:59:46] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[04/Jan/2019 15:59:47] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[04/Jan/2019 15:59:47] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[04/Jan/2019 15:59:50] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[04/Jan/2019 15:59:51] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[04/Jan/2019 15:59:51] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[04/Jan/2019 23:32:15] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[04/Jan/2019 23:32:16] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[04/Jan/2019 23:32:16] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[04/Jan/2019 23:32:19] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[04/Jan/2019 23:32:20] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[04/Jan/2019 23:32:20] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[09/Jan/2019 16:16:08] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[09/Jan/2019 16:16:10] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[09/Jan/2019 16:16:10] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[09/Jan/2019 16:16:12] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[09/Jan/2019 16:16:13] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[09/Jan/2019 16:16:13] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:40:05] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:40:07] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[19/Jan/2019 13:40:07] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:40:10] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:40:11] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[19/Jan/2019 13:40:11] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:42:04] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:42:05] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[19/Jan/2019 13:42:05] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:42:07] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:42:08] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[19/Jan/2019 13:42:08] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[19/Jan/2019 13:43:08] WARNING [django.server:124] "GET /api/user-requests HTTP/1.1" 403 55
[19/Jan/2019 13:43:41] ERROR [django.request:135] Internal Server Error: /api/user-requests
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\core_main_app\utils\decorators.py", line 186, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\core_website_app\rest\account_request\views.py", line 30, in get_all
    if serializer.is_valid():
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\serializers.py", line 230, in is_valid
    'Cannot call `.is_valid()` as no `data=` keyword argument was '
AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
[19/Jan/2019 13:43:41] ERROR [django.server:124] "GET /api/user-requests HTTP/1.1" 500 22163
[19/Jan/2019 13:43:41] ERROR [django.request:135] Internal Server Error: /api/user-requests
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\core_main_app\utils\decorators.py", line 186, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\core_website_app\rest\account_request\views.py", line 30, in get_all
    if serializer.is_valid():
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\serializers.py", line 230, in is_valid
    'Cannot call `.is_valid()` as no `data=` keyword argument was '
AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
[19/Jan/2019 13:43:41] ERROR [django.server:124] "GET /api/user-requests HTTP/1.1" 500 22163
[19/Jan/2019 13:45:29] WARNING [django.server:124] "POST /api/user-request/accept HTTP/1.1" 400 47
[19/Jan/2019 13:45:42] ERROR [django.request:135] Internal Server Error: /api/user-requests
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\core_main_app\utils\decorators.py", line 186, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\core_website_app\rest\account_request\views.py", line 30, in get_all
    if serializer.is_valid():
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\serializers.py", line 230, in is_valid
    'Cannot call `.is_valid()` as no `data=` keyword argument was '
AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
[19/Jan/2019 13:45:42] ERROR [django.server:124] "GET /api/user-requests HTTP/1.1" 500 22163
[19/Jan/2019 14:04:43] WARNING [django.request:152] Not Found: /docs/api/authentificate
[19/Jan/2019 14:04:43] WARNING [django.server:124] "GET /docs/api/authentificate HTTP/1.1" 404 11766
[19/Jan/2019 14:04:44] WARNING [django.request:152] Not Found: /favicon.ico
[19/Jan/2019 14:04:44] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 11730
[30/Jan/2019 21:03:16] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[30/Jan/2019 21:03:18] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[30/Jan/2019 21:03:18] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[30/Jan/2019 21:03:21] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[30/Jan/2019 21:03:22] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[30/Jan/2019 21:03:22] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 08:31:35] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 08:31:36] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 08:31:36] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 08:31:40] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 08:31:41] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 08:31:41] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 08:48:55] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 08:48:56] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 08:48:56] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 08:52:48] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 59
[01/Feb/2019 09:15:04] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:15:05] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:15:05] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:15:30] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() takes exactly 3 arguments (2 given)
[01/Feb/2019 09:15:30] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 21376
[01/Feb/2019 09:17:37] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:17:38] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:17:38] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:17:44] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 59
[01/Feb/2019 09:18:28] WARNING [django.server:124] "POST /rest/workspace/ HTTP/1.1" 400 51
[01/Feb/2019 09:18:58] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:18:59] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:18:59] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:19:08] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 84
[01/Feb/2019 09:19:36] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:19:37] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:19:37] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:20:48] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:20:49] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:20:49] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:21:03] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 84
[01/Feb/2019 09:21:44] WARNING [django.server:124] "GET /rest/data/get-full HTTP/1.1" 400 47
[01/Feb/2019 09:23:00] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:23:01] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:23:01] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:23:12] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 84
[01/Feb/2019 09:23:59] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:24:00] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:24:00] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:24:09] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\mdcs\MDCS-master\rest\views.py", line 58, in get
    data_object_list = data_api.get_all_by_workspace(workspace_api.get_by_id("5c13e1f45b04bf25ec02402e"))
  File "C:\Users\HP\Anaconda2\lib\site-packages\core_main_app\utils\access_control\decorators.py", line 33, in wrapper
    return check_func(func, *args, **kwargs)
TypeError: can_read_or_write_data_workspace() takes exactly 3 arguments (2 given)
[01/Feb/2019 09:24:09] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 21770
[01/Feb/2019 09:25:03] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:25:04] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:25:04] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:26:48] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:26:49] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:26:49] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:28:02] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:28:03] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:28:03] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:29:29] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:29:30] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:29:30] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:30:20] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:30:21] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:30:21] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:30:39] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:30:40] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:30:40] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:31:30] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:31:31] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:31:31] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:31:49] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:31:50] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:31:50] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:32:06] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:32:08] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:32:08] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:32:44] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:32:45] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:32:45] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:33:49] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:33:50] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:33:50] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:34:14] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:34:15] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:34:15] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:39:30] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:39:31] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:39:31] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:39:48] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:02] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:40:03] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:40:03] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:40:21] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:23] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:25] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:26] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:26] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:26] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:26] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:27] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:27] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:27] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:28] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:28] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:28] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:40:28] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:41:51] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:41:52] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:41:52] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:41:52] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:41:53] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:41:53] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:41:53] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:42:09] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 09:47:25] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:47:26] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:47:26] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:49:51] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:49:52] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:49:52] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:50:00] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:50:01] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:50:01] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:50:13] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:50:14] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:50:14] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:52:42] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:52:43] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:52:43] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:53:06] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:53:07] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:53:07] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:53:17] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:53:18] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:53:18] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:55:07] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:55:08] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:55:08] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:00] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:01] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:56:01] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:30] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:31] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:56:31] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:33] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:34] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:56:34] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:47] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:56:48] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:56:48] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:57:46] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 09:57:47] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 09:57:47] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:00:54] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:00:55] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:00:55] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:01:57] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:01:58] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:01:58] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:02:43] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:02:44] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:02:44] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:24:27] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:24:28] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:24:28] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:24:50] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:24:52] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:24:52] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:25:43] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:25:44] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:25:44] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:26:04] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() takes exactly 3 arguments (2 given)
[01/Feb/2019 10:26:04] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 21376
[01/Feb/2019 10:27:52] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:27:53] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:27:53] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:28:00] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() takes exactly 3 arguments (2 given)
[01/Feb/2019 10:28:01] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 21376
[01/Feb/2019 10:37:17] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() takes exactly 3 arguments (2 given)
[01/Feb/2019 10:37:17] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 20999
[01/Feb/2019 10:37:19] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() takes exactly 3 arguments (2 given)
[01/Feb/2019 10:37:19] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 20999
[01/Feb/2019 10:37:21] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() takes exactly 3 arguments (2 given)
[01/Feb/2019 10:37:21] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 20999
[01/Feb/2019 10:37:22] ERROR [django.request:135] Internal Server Error: /mdcs/data/
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Anaconda2\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() takes exactly 3 arguments (2 given)
[01/Feb/2019 10:37:22] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 20999
[01/Feb/2019 10:44:10] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:44:11] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:44:11] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:50:06] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:50:59] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:51:00] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:51:00] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:51:02] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:51:03] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:51:03] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:51:24] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:51:25] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:51:25] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:51:48] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:51:49] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:51:49] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:52:01] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 52
[01/Feb/2019 10:53:31] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:53:32] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:53:32] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:53:37] ERROR [django.server:124] "GET /mdcs/data/ HTTP/1.1" 500 78
[01/Feb/2019 10:54:08] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:54:09] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:54:09] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:57:36] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:57:37] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:57:37] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:57:57] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:57:58] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:57:58] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:58:21] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:58:22] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:58:22] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:58:41] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 10:58:42] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 10:58:42] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:04:04] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:04:05] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:04:05] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:06:47] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:06:48] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:06:48] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:07:15] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:07:16] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:07:16] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:08:12] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:08:13] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:08:13] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:08:34] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:08:35] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:08:35] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:09:50] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:09:51] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:09:51] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:09:54] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:09:55] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:09:55] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:10:47] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:10:48] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:10:48] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:10:57] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:10:58] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:10:58] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:11:00] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:11:01] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:11:01] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:11:22] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:11:23] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:11:23] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:12:25] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:12:26] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:12:26] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:12:59] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:13:00] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:13:00] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:13:09] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:13:10] INFO [core_oaipmh_harvester_app.tasks:128] Impossible to retrieve scheduled tasks. Is Celery started?
[01/Feb/2019 11:13:10] INFO [core_oaipmh_harvester_app.tasks:129] FINISH revoking OAI-PMH scheduled tasks.
[01/Feb/2019 11:15:08] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.
